### ISSUE TITLE
Question: is it an usecase for this container? 

### ISSUE THREAD

**Issue by shahram7** [httptoolkit/docker-socks-tunnel#2]
Hi, 
fist of all sorry if my question is inappropriate. I have a download manager which doesn't support socks proxies. can I config this container an make the download manager to use the network of docker-socks-tunnel? best regards

**Comment by pimterry** [comment]
Hi @shahram7. No, I don't think this will do what you want. This container is designed to tunnel traffic _info_ a Docker network by hosting a SOCKS proxy there. It doesn't help with traffic for clients that don't support SOCKS proxies unfortunately.
